name: Building

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 g++ make
      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.3.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
