name: Generating static site

on:
  workflow_call:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.3.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run generate
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
