name: Optimized CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint:
    uses: ./.github/workflows/lint.yml
    needs: setup

  build:
    uses: ./.github/workflows/build.yml
    needs: setup

  generate:
    uses: ./.github/workflows/generate.yml
    needs: build

  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: generate
