name: Setup Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.get-node.outputs.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install native build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 g++ make

      - name: Use PNPM
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js
        id: get-node
        uses: actions/setup-node@v4.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
